### ISSUE TITLE
Support AWS Signer for  Private Key (secp256k1)

### ISSUE THREAD

**Issue by distributedstatemachine** [axonweb3/axon#1136]
### Contact Details

sam@tunnelvisionlabs.xyz

### Propose-a-new-feature

Describe the solution you'd like:

# Problem Statement

Axon nodes are required to have access to  sep256k1 key in order to [make authenticated peer connections](https://github.com/axonweb3/axon/blob/b1e0476da57ded845779032ac9fbb7c8da60571c/core/network/src/service.rs#L345). However , the currently codebase does not lend itself to security best practices , as these keys are currently exposed transparently in the [node's config file](https://github.com/axonweb3/axon/blob/b1e0476da57ded845779032ac9fbb7c8da60571c/common/config-parser/src/types.rs#L233) . 

# Proposed Solution

Axon using ethers.rs , which implement the [AWS Signer](https://github.com/gakonst/ethers-rs/tree/d80e82a561ff714d1fa10c05786bb6fe124edbf0/ethers-signers/src/aws). 

# Implementation

Inspiration for implementing the AWS signer can be taken from [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/aea77a10f79cafddd1856285b3696b99201d4b8f/rust/hyperlane-base/src/settings/signers.rs#L16)

### Alternatives you've considered

As we use kuberenetes for our set up , we could store them as encrypted secrets , but this presents two issues

1. Secrets are base64 encoded.
2. Even with [Secret Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html) , the axon nodes have no way of parsing these secrets

### Anything else?

This is a blocker to going to production and would appreciate your assistance with it.

**Comment by KaoImin** [comment]
Thank you for your suggestion. The private key specified in the configuration file is primarily used for signing p2p messages. It is a requirement for SecIO, which is used in the Tentacle library. Unfortunately, the AWS signer does not support this functionality.

**Comment by KaoImin** [comment]
We will start to develop this feature in next week.

**Comment by serejke** [comment]
@KaoImin @driftluo team, before you start actively working on this, we'd like to clarify the following:

Axon uses the same private key (`privkey` specified in config.toml) for 2 purposes: 
1. secio p2p protocol, which uses `sep256k1` curve
https://github.com/axonweb3/axon/blob/fce5bf26c971b8adb1e9ea5b06f74f891c2a112f/core/run/src/lib.rs#L263
2. Axon protocol, which uses `BLS12-381` curve https://github.com/axonweb3/axon/blob/fce5bf26c971b8adb1e9ea5b06f74f891c2a112f/core/run/src/lib.rs#L439

I double checked how the `privkey` is generated in the `axon-cli`:
- generate random key [here](https://github.com/axonweb3/axon-cli/blob/7fb73f704e1393257237d899c8bfd0924462029e/src/axon_nodes/config.rs#L125)
- derive `KeyPair` for secp and BLS [here](https://github.com/axonweb3/axon-cli/blob/7fb73f704e1393257237d899c8bfd0924462029e/src/axon_nodes/config.rs#L86-L85)

Our original request is to avoid configuring any security keys in the `config.toml`, and have an application level key-signing service integration (like AWS KMS or HashicorpVault).

In this ticket we requested AWS KMS Signer key integration, but the problem is AWS KMS [does not support](https://aws.amazon.com/kms/faqs/) BLS key signing. It means that you cannot use KMS for the Axon protocol signing. Only the secio protocol can use the KMS. 

But given the private key is currently used by both, the Axon protocol also needs to be integrated with key signer.

[HashiCorp Vault](https://www.hashicorp.com/resources/hashicorp-vault-for-crypto-agility) supports BLS key signing, and we may set up an infrastructure with a Vault serving the Axon protocol and p2p. My question: is it an absolute requirement that the private key is reused for both "subsystems"? If so, KMS is a no go anyway, and only the HashiCorp Vault would work.

We'd like to hear your thoughts.

**Comment by driftluo** [comment]
https://docs.rs/hashicorp_vault/2.1.1/hashicorp_vault/client/struct.VaultClient.html#method.list_secrets 

I searched for related client implementations. This is a plaintext query. Although there is encrypted transmission, the private key cannot be directly stored here, nor can it be signed.

**Comment by serejke** [comment]
@driftluo correct me if I'm wrong, but the Vault's idea is not store private key and transfer it to the client when necessary.

It is to generate and store the private key in a secure and inaccessible location — and provide HTTP API `sign(<message>)` that can be called by applications (Axon protocol) to sign a specific message.

**Comment by distributedstatemachine** [comment]
@driftluo maybe this might offer some inspiration. Prsym integrates a remote vault signer with this : https://github.com/prysmaticlabs/remote-signer/blob/master/keyvault/vault.go

**Comment by KaoImin** [comment]
This is support in #1182
