### ISSUE TITLE
Analyze the failed test (Contract: DoubleEndedQueue) in workflows/openzeppelin_test_16_19.yml

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1412]
https://github.com/axonweb3/axon/actions/workflows/openzeppelin_test_16_19.yml 的 Contract: DoubleEndedQueue failed to run twice:

### ProviderError: Custom error: can not get receipt

1. https://github.com/axonweb3/axon/actions/runs/6093863030/job/16534301433#step:15:91
2. https://github.com/axonweb3/axon/actions/runs/6093672541/job/16533737625#step:15:140

**Comment by KaoImin** [comment]
As the describe in https://github.com/cryptape/acceptance-internal/issues/419, if querying for receipts for transactions in the pool,  Axon should return `Null` rather than error.
Thus the method that can fix this bug is that if get `None` from storage, check the `mempool` again. To be notice that the process of insert a transaction to `mempool` contains two stage:
1. Insert to a co-queue
2. Insert all transactions in the co-queue to mempool

Only the transactions that inserted into `mempool` can be query by `contain()` method. However, the interval of drain co-queue is 50 ms.

**Comment by sunchengzhu** [comment]
### Why does this issue occur intermittently?

#### Transactions will go through these three states:
The transaction has not been executed.
The transaction has been executed but not saved to `storage`.
The transaction has been executed and saved to `storage`.

Previously, since we did not check the transaction in the `mempool`, using `eth_getTransactionReceipt` to query the receipt when the transaction is in the second state will cause an error. Therefore, the test case succeeds in retrieving the receipt when the transaction is in states 1 and 3, and fails when it's in state 2.
