### ISSUE TITLE
Failed to pull image ghcr.io/simon-tl/blockscan:latest

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1458]
# Related code
https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/devtools/chain/docker-compose.yml#L21-L23

## CMD in [A Gitpod workspace](https://gitpod.io/workspaces)
```bash
docker pull ghcr.io/simon-tl/blockscan:latest 
latest: Pulling from simon-tl/blockscan
213ec9aee27d: Pull complete 
80bd163d4d5d: Pull complete 
6a7ab4f61ae4: Pull complete 
b361c6d91340: Pull complete 
6ccebd83747b: Pull complete 
9da784d1e463: Pull complete 
4f4fb700ef54: Pull complete 
f0e86bc98481: Pull complete 
119327546d55: Pull complete 
9881d174f9f8: Pull complete 
733053714b2e: Pull complete 
a56bf1a30079: Pull complete 
dc141007ccad: Pull complete 
f16376bc99fa: Extracting [==================================================>]  6.081MB/6.081MB
4054c2ea024b: Download complete 
3961042e6484: Download complete 
```

## Error
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/node_modules/tmp/LICENSE" for UID 2119470584, GID 2042662593 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/tmp/LICENSE: invalid argument

**Comment by sunchengzhu** [comment]
~~> We can only build images that use UIDs < 65534 due to user namespaces.~~

~~If we want to pull this image in Gitpod, as [the solution](https://circleci.com/docs/high-uid-error/#solution) mentioned in [the comment](https://github.com/gitpod-io/gitpod/issues/2649#issuecomment-753977185), we need to `update the files' UID/GID and recreate the image`.~~

> pm2 depends on nssocket which owns files with an arbitrarily large uid/gid. That breaks on docker rootless mode: https://github.com/moby/moby/issues/43576

We encountered a similar issue when running Godwoken Kicker on Gitpod, manifesting as an error similar to the one described. We managed to resolve the one by removing pm2. However, since the error didn't pinpoint the exact package causing the issue, we're still uncertain about a complete resolution.
![image](https://user-images.githubusercontent.com/36075573/230869936-468b1be3-b620-4e4a-a04e-1bc260b7e0ac.png)
