### ISSUE TITLE
Why sync nodes need BLS keys? -> try to remove privkey_file requirement in a sync node

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1497]

**Comment by chaoticlonghair** [comment]
I think this issue is related to #1511.
These two issues should be considered together.

**Comment by Flouse** [comment]
### @KaoImin 's explanation
Since Axon's validator list may change, a sync node may become a validator node in certain situations.
Therefore, the requirement for BLS keys in sync nodes is essential for maintaining the flexibility of the network.

## Thought

While Axon could potentially add a "sync-mode-only" configuration and make the BLS key config optional in this mode, this is not part of the current development plan.

Let's watch the feedback and decide if we should do this later.
