### ISSUE TITLE
Asking for a magic string in BLS signature: where does it come from?

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1508]
### What happened

I met a problem to sync blocks from a observer node.

It throws an error of `invalid signature`.

When I tried to write a unit test, I found the magic string `"axon"`.

Before the following line:
https://github.com/axonweb3/axon/blob/9a0bdbd93e15b6ea5f02f89f197a3cdde6c9089e/core/consensus/src/util.rs#L240

There is no string of `"axon"` is used for creating the signature, why it is used for verifying the signature?

Where does this magic string come from?

I haven't found the original repository `ophelia_blst` (ref: #1507).

https://github.com/axonweb3/axon/blob/9a0bdbd93e15b6ea5f02f89f197a3cdde6c9089e/common/crypto/src/lib.rs#L6

**Comment by KaoImin** [comment]
The origin source is [here](https://github.com/zeroqn/ophelia). 
Axon used another bls library which need a _common_ref_ to sign and verify. The current blst library doesn't need this. In order to keep the interface be same, we keep the argument, however, it's useless and we use "axon" to take place.
