### ISSUE TITLE
A chain with single validator could be increased even I set an INCORRECT `bls_pub_key`.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1509]
### Description

I have made a mistake:
- I used [an incorrect `bls_pub_key`](https://github.com/axonweb3/axon/commit/7de3eb42f2b48506a5c1d1f60ba02f4ec1f017cc) in `params.verifier_list` to initialize a chain, but the `bls_privkey_file` is correct.

So, the `bls_privkey_file` didn't match any keys in metadata.
The chain should be an observer, its height shouldn't be increased.

But, in fact, the chain is running as a normal chain.

The only issue is that no observers are able to connect to this node.

### Reproduce

I only changes the file `devtools/chain/specs/single_node/chain-spec.toml`:

https://github.com/axonweb3/axon/blob/9a0bdbd93e15b6ea5f02f89f197a3cdde6c9089e/devtools/chain/specs/single_node/chain-spec.toml#L80

with the following patch:

```diff
- bls_pub_key = "0xa26e3fe1cf51bd4822072c61bdc315ac32e3d3c2e2484bb92942666399e863b4bf56cf2926383cc706ffc15dfebc85c6"
+ bls_pub_key = "0xac85bbb40347b6e06ac2dc2da1f75eece029cdc0ed2d456c457d27e288bfbfbcd4c5c19716e9b250134a0e76ce50fa22"
```

And the chain [works well in CI](https://github.com/axonweb3/axon/actions/runs/6665037276/job/18113829044).

**Comment by Flouse** [comment]
@driftluo  can you confirm that if this is a bug?

**Comment by driftluo** [comment]
I personally think the problem lies here. If the proposal is made by oneself, proof verification is not performed：
@KaoImin 

https://github.com/axonweb3/axon/blob/527ccdfed76e1fd24b508fbda6be5594ff10c190/core/consensus/src/engine.rs#L207-L215

https://github.com/axonweb3/axon/blob/527ccdfed76e1fd24b508fbda6be5594ff10c190/core/consensus/src/engine.rs#L570-L580

**Comment by KaoImin** [comment]
> I personally think the problem lies here. If the proposal is made by oneself, proof verification is not performed： @KaoImin
> 
> https://github.com/axonweb3/axon/blob/527ccdfed76e1fd24b508fbda6be5594ff10c190/core/consensus/src/engine.rs#L207-L215
> 
> https://github.com/axonweb3/axon/blob/527ccdfed76e1fd24b508fbda6be5594ff10c190/core/consensus/src/engine.rs#L570-L580

I suggest check the bls key is correct when init.

**Comment by Flouse** [comment]
## For the single Axon node mode
@driftluo has explained: If the proposal is made by oneself, proof verification is not performed.

This mode could be ignored because in a paractical chain, the single node mode won't be used.
Just be sure to setup a right key in this mode. I think a better key-generator tool will help.
- https://github.com/axonweb3/axon/pull/1621


## For the multi Axon nodes mode
If one of the `bls_pub_key`s in chain-spec.toml is wrong, then [`verify_proof` function will failed](https://github.com/axonweb3/axon/blob/c9b035eed187f317ad886726570c37c369113ac2/core/consensus/src/adapter.rs#L541-L551), and the error message `[consensus] verify_proof_signature error` will be displayed.

**Comment by Flouse** [comment]
> @KaoImin suggested that checking the bls key is correct when init.

But during the init step, the program doesn't know if [the bls_privkey_file in config.toml](https://github.com/axonweb3/axon/blob/c9b035eed187f317ad886726570c37c369113ac2/devtools/chain/config.toml#L6-L7) is associated with a validator, so it can't just check if the bls_pub_key is the configured bls_privkey's pub key.
